apiVersion: apps/v1
kind: Deployment
metadata:
  name: lernprojekt-app
  labels:
    app: lernprojekt-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lernprojekt-app
  template:
    metadata:
      labels:
        app: lernprojekt-app
    spec:
      containers:
        - name: lernprojekt-app
          image: lernprojekt-app:0.2.0
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: lernprojekt-config
            - secretRef:
                name: lernprojekt-secret
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 15
