apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lernprojekt

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - redis-pvc.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - hpa.yaml
  - ingress.yaml
  - networkpolicy.yaml
  - pdb.yaml
