apiVersion: apps/v1
kind: Deployment
metadata:
  name: lernprojekt-app
  namespace: lernprojekt
  labels:
    app: lernprojekt-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lernprojekt-app
  template:
    metadata:
      labels:
        app: lernprojekt-app
    spec:
      containers:
        - name: lernprojekt-app
          image: lernprojekt-app:0.1.0
          ports:
            - containerPort: 5000
          env:
            - name: APP_VERSION
              value: "0.1.0"
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
